version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shorturlapi
    volumes:
      - redis-data:/data
    command: ["redis-server"]
      
  shorturl-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on: 
      - redis
    working_dir: /go/shorturlapi
    networks:
      - shorturlapi
    env_file:
      - env.conf
    volumes:
      - ./:/go/shorturlapi
    ports:
      - 8080:8080
    command: go run main.go

networks:
  shorturlapi:
      name: shorturlapi

volumes:
  redis-data: